### ISSUE TITLE
Sitting on blocks from furniture mod doesn't lock you in proper position and show sitting animation

### ISSUE THREAD

**Issue by wed15** [Meldexun/EntityDesyncFix#2]
When EntityDesyncFix mod is installed sitting function is broken with some chair-like blocks from other mods.(Not every mods with chair seem to be affected though) Sitting on those block doesn't lock your position on the chair with sitting animation. Instead player can move around the world freely and dismounting teleports player back to chair's position. This happens with only EntityDesyncFix, mixinbooter and furniture mods. 

[Video demonstration of the issue (imgur)](https://imgur.com/ZZ1xkpY)

**Versions**
Forge 14.23.5.2860
EntityDesyncFix-1.12.2-1.0.1
!mixinbooter-4.2
[MrCrayfish's Furniture Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/2749993) 6.3.1
[How 'Bout That Furniture](https://www.curseforge.com/minecraft/mc-mods/how-bout-that-furniture/files/2479282) 2.0.3

**Log File**
[log](https://gist.github.com/wed15/a54d1a73dd2fd906bd6cad113119cc2f)
[debug.log](https://gist.github.com/wed15/c0bded3bce7e7de5f95d34bea0377a1c)

**Comment by Meldexun** [comment]
Fixed in v1.12.2-1.0.2

**Comment by InuYasha86000** [comment]
Unfortunately this bug still exists with version 1.0.3, the mods affected are bibliocraft 2.4.6 and mr crayfish's furniture 6.3.2. removing the mod made the chairs work properly again. was using it on my modpack server linked here if needed for testing: https://www.curseforge.com/minecraft/modpacks/the-valley-1-12-2

**Comment by Meldexun** [comment]
There is no version 1.0.3

If there is an issue for you please try to reproduce the issue with as few other mods as possible. Recording a video of the issue might also be helpful (you can also go into the mod options to show what version of EntityDesyncFix you are using). A log file also might give additional insights.

**Comment by InuYasha86000** [comment]
I will set up a test hopefully soon as my modpack has 175 mods in it. also I don't know what I was seeing, you are right it is version 1.0.2. however just thinking about it, I run a hybrid Mhoist server which could be causing issues with entity desync, if it helps any the server version is mohist-1.12.2-321
